version: '3'
services:
  nextjs:
    container_name: nextjs 
    build:
      context: .
      dockerfile: ./dockerfiles/nextjs.dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./nextjs/:/nextjs
      # exclude volumes
      - /nextjs/node_modules
    tty: true
    stdin_open: true

  express:
    container_name: express
    build:
      context: .
      # Dockerfileがビルドされる時のカレントディレクトリはdocker build DIRで指定したDIRである。
      dockerfile: ./dockerfiles/express.dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./express/:/usr/src/app
      # exclude volumes
      - /usr/src/app/node_modules
    tty: true
    stdin_open: true
